version: 0.2
# GitHub -> CodeBuild -> S3 -> CloudFront
phases:
  install:
    commands:
      - echo update npm...
      - npm update -g npm
      - echo node -v
      - node -v
      - echo npm -v
      - npm -v
  pre_build:
    commands:
      - echo Installing source NPM dependencies...!
      - npm install --prefix ./front-vue
  build:
    commands:
      - echo build start
      - npm --prefix ./front-vue run build
      - echo build completed
  post_build:
    commands:
      - echo Delete S3 Bucket object...
      - aws s3 rm s3://${S3_BUCKET_NAME} --recursive
      - aws s3 sync ./front-vue/dist/  s3://${S3_BUCKET_NAME} 
#artifacts:
#  files:
#    - '**/*'
#  base-directory: 'front-vue/dist'